import { UpstreamError, identify } from './gemini';
import { verifySubscription } from './play';
import { QuotaStore, SCANS_PER_AD, type Quota } from './quota';

export interface Env {
  QUOTA: KVNamespace;
  GEMINI_API_KEY: string;
  GEMINI_MODEL?: string;
  PLAY_SERVICE_ACCOUNT_EMAIL: string;
  PLAY_PRIVATE_KEY: string;
  ANDROID_PACKAGE_NAME: string;
}

/** Roughly 8MB of base64, well above a 720p JPEG. */
const MAX_IMAGE_CHARS = 8_000_000;

const CORS = {
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'content-type,x-device-id',
  'access-control-allow-methods': 'GET,POST,OPTIONS',
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json', ...CORS },
  });
}

function quotaView(quota: Quota) {
  return {
    limit: quota.limit,
    // The app only needs to know "lots", not MAX_SAFE_INTEGER.
    remaining: quota.entitled ? -1 : quota.remaining,
    ad_credit_available: quota.adCreditAvailable,
    scans_per_ad: SCANS_PER_AD,
    entitled: quota.entitled,
    entitled_until: quota.entitledUntil ?? null,
  };
}

/**
 * Anonymous per-install identifier, generated by the app. Good enough to meter
 * a free tier; someone who reinstalls gets a fresh allowance. Tightening that
 * means Play Integrity or requiring sign-in, both of which cost you installs,
 * so it is a deliberate trade rather than an oversight.
 */
function deviceId(request: Request): string | null {
  const id = request.headers.get('x-device-id')?.trim();
  if (!id || id.length < 16 || id.length > 128) return null;
  return id;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    const url = new URL(request.url);
    const device = deviceId(request);
    if (!device) {
      return json({ error: 'missing_device_id' }, 400);
    }

    const quotas = new QuotaStore(env.QUOTA);

    try {
      switch (`${request.method} ${url.pathname}`) {
        case 'GET /v1/quota':
          return json({ quota: quotaView(await refreshed(device, quotas, env)) });

        case 'POST /v1/identify':
          return await handleIdentify(request, device, quotas, env);

        case 'POST /v1/ad-credit':
          return await handleAdCredit(device, quotas);

        case 'POST /v1/subscription':
          return await handleSubscription(request, device, quotas, env);

        default:
          return json({ error: 'not_found' }, 404);
      }
    } catch (error) {
      console.error(error);
      return json({ error: 'server_error' }, 500);
    }
  },
};

/**
 * Re-checks a stored purchase with Google once its recorded expiry has passed,
 * so a renewal extends access without the app doing anything.
 */
async function refreshed(
  device: string,
  quotas: QuotaStore,
  env: Env,
): Promise<Quota> {
  const quota = await quotas.get(device);
  if (quota.entitled) return quota;

  const stored = await quotas.storedPurchase(device);
  if (!stored) return quota;

  try {
    const entitlement = await verifySubscription(stored.purchaseToken, env);
    if (!entitlement.active) return quota;

    return await quotas.setEntitlement(device, {
      entitledUntil: entitlement.expiresAt,
      productId: entitlement.productId || stored.productId,
      purchaseToken: stored.purchaseToken,
    });
  } catch (error) {
    // A Play outage must not lock a paying user out of the app.
    console.error('Entitlement refresh failed', error);
    return quota;
  }
}

async function handleIdentify(
  request: Request,
  device: string,
  quotas: QuotaStore,
  env: Env,
): Promise<Response> {
  const body = (await request.json().catch(() => null)) as {
    image_base64?: string;
    mime_type?: string;
  } | null;

  const image = body?.image_base64;
  if (!image || image.length > MAX_IMAGE_CHARS) {
    return json({ error: 'bad_image' }, 400);
  }

  await refreshed(device, quotas, env);

  const spent = await quotas.spend(device);
  if (!spent) {
    return json(
      { error: 'quota_exhausted', quota: quotaView(await quotas.get(device)) },
      429,
    );
  }

  try {
    const identification = await identify(
      image,
      body?.mime_type ?? 'image/jpeg',
      env,
    );
    return json({ identification, quota: quotaView(spent) });
  } catch (error) {
    // Never charge someone a scan for our own failure.
    await quotas.refund(device);

    if (error instanceof UpstreamError) {
      return json(
        { error: 'upstream_failed', message: error.message, retryable: error.retryable },
        502,
      );
    }
    throw error;
  }
}

async function handleAdCredit(
  device: string,
  quotas: QuotaStore,
): Promise<Response> {
  const granted = await quotas.grantAdCredit(device);
  if (!granted) {
    return json(
      { error: 'ad_credit_used', quota: quotaView(await quotas.get(device)) },
      429,
    );
  }
  return json({ quota: quotaView(granted) });
}

async function handleSubscription(
  request: Request,
  device: string,
  quotas: QuotaStore,
  env: Env,
): Promise<Response> {
  const body = (await request.json().catch(() => null)) as {
    purchase_token?: string;
    product_id?: string;
  } | null;

  if (!body?.purchase_token) {
    return json({ error: 'missing_purchase_token' }, 400);
  }

  const entitlement = await verifySubscription(body.purchase_token, env);
  if (!entitlement.active) {
    return json(
      { error: 'purchase_not_active', quota: quotaView(await quotas.get(device)) },
      402,
    );
  }

  const quota = await quotas.setEntitlement(device, {
    entitledUntil: entitlement.expiresAt,
    productId: entitlement.productId || body.product_id || '',
    purchaseToken: body.purchase_token,
  });

  return json({ quota: quotaView(quota) });
}
